// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Blog = Collections['posts']['schema']['_output']
export declare const posts: Blog[]

export type Changelog = Collections['changelogItems']['schema']['_output']
export declare const changelogItems: Changelog[]
